excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - HAVITests
identifier_name:
  allowed_symbols: "_"
disabled_rules:
  - variable_name
  - line_length
  - trailing_whitespace
  - cyclomatic_complexity
line_length:
  ignores_comments: true
  ignoresInterpolatedStrings: true
line_length: 280
function_body_length:
  - 200 # warning
  - 300 # error
